CREATE TABLE `zokodaily_property` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `site` varchar(100) NOT NULL COMMENT 'source website',
  `source_id` bigint DEFAULT NULL COMMENT 'source platform listing id',
  `guid` varchar(64) NOT NULL DEFAULT '' COMMENT 'source guid',
  `section_key` varchar(100) NOT NULL COMMENT 'section key',
  `section_name` varchar(100) NOT NULL COMMENT 'section name',
  `category_name` varchar(100) DEFAULT '' COMMENT 'category name',
  `category_slug` varchar(100) DEFAULT '' COMMENT 'category slug',
  `title` varchar(255) NOT NULL COMMENT 'listing title',
  `price_amount` decimal(18,2) DEFAULT NULL COMMENT 'listing price',
  `currency` varchar(16) DEFAULT '' COMMENT 'currency',
  `price_text` varchar(128) DEFAULT '' COMMENT 'formatted price',
  `price_type` varchar(64) DEFAULT '' COMMENT 'price type',
  `price_period` varchar(64) DEFAULT '' COMMENT 'price period',
  `region_name` varchar(128) DEFAULT '' COMMENT 'region name',
  `region_slug` varchar(128) DEFAULT '' COMMENT 'region slug',
  `region_text` varchar(255) DEFAULT '' COMMENT 'full region text',
  `description` longtext COMMENT 'listing description',
  `url` varchar(500) NOT NULL COMMENT 'listing url',
  `estate_name` varchar(128) DEFAULT '' COMMENT 'estate name',
  `property_type` varchar(128) DEFAULT '' COMMENT 'property type',
  `property_size` varchar(64) DEFAULT '' COMMENT 'property size value',
  `property_size_unit` varchar(32) DEFAULT '' COMMENT 'property size unit',
  `bedrooms` varchar(32) DEFAULT '' COMMENT 'bedrooms',
  `bathrooms` varchar(32) DEFAULT '' COMMENT 'bathrooms',
  `furnishing` varchar(64) DEFAULT '' COMMENT 'furnishing',
  `parking_spot` varchar(128) DEFAULT '' COMMENT 'parking spot',
  `status_of_construction` varchar(128) DEFAULT '' COMMENT 'construction status',
  `seller_id` bigint DEFAULT NULL COMMENT 'seller id',
  `seller_guid` varchar(64) DEFAULT '' COMMENT 'seller guid',
  `seller_name` varchar(255) DEFAULT '' COMMENT 'seller name',
  `seller_page_url` varchar(500) DEFAULT '' COMMENT 'seller page url',
  `seller_phone` varchar(64) DEFAULT '' COMMENT 'seller phone',
  `seller_response_time` varchar(255) DEFAULT '' COMMENT 'seller response time',
  `seller_last_seen` varchar(128) DEFAULT '' COMMENT 'seller last seen',
  `view_count` int NOT NULL DEFAULT '0' COMMENT 'views',
  `fav_count` int NOT NULL DEFAULT '0' COMMENT 'favorites',
  `count_images` int NOT NULL DEFAULT '0' COMMENT 'image count',
  `is_promoted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'is promoted',
  `is_negotiable` bit(1) NOT NULL DEFAULT b'0' COMMENT 'is negotiable',
  `is_active` bit(1) NOT NULL DEFAULT b'1' COMMENT 'is active',
  `is_closed` bit(1) NOT NULL DEFAULT b'0' COMMENT 'is closed',
  `posted_at_raw` varchar(128) DEFAULT '' COMMENT 'relative posted time',
  `date_created` datetime DEFAULT NULL COMMENT 'created at on source',
  `date_moderated` datetime DEFAULT NULL COMMENT 'moderated at on source',
  `attrs_json` longtext COMMENT 'listing attributes',
  `labels_json` longtext COMMENT 'listing labels',
  `seller_labels_json` longtext COMMENT 'seller labels',
  `breadcrumbs_json` longtext COMMENT 'breadcrumbs',
  `safety_tips_json` longtext COMMENT 'safety tips',
  `raw_payload_json` longtext COMMENT 'raw source payload',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'creator',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'updater',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'is deleted',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT 'tenant id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_site_guid` (`site`,`guid`),
  UNIQUE KEY `uniq_site_url` (`site`,`url`),
  KEY `idx_section_key` (`section_key`),
  KEY `idx_region_slug` (`region_slug`),
  KEY `idx_seller_id` (`seller_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ghana property listings';

CREATE TABLE `zokodaily_property_image` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `property_id` bigint NOT NULL COMMENT 'related property id',
  `image_id` bigint DEFAULT NULL COMMENT 'source image id',
  `source_url` varchar(500) DEFAULT NULL COMMENT 'source image url',
  `local_path` varchar(500) DEFAULT NULL COMMENT 'downloaded local path',
  `alt_text` varchar(255) DEFAULT '' COMMENT 'image alt text',
  `is_main` bit(1) NOT NULL DEFAULT b'0' COMMENT 'is main image',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT 'image order',
  `width` int DEFAULT NULL COMMENT 'image width',
  `height` int DEFAULT NULL COMMENT 'image height',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'creator',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'updater',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'is deleted',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT 'tenant id',
  PRIMARY KEY (`id`),
  KEY `idx_property_id` (`property_id`),
  UNIQUE KEY `uniq_property_source_url` (`property_id`,`source_url`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ghana property images';
